import { Question } from '../types'

export const attentionQuestions: Question[] = [
  // ===== DIFFICULTY 1 — Easy (5 questions) =====
  {
    id: 'att-e1',
    type: 'attention',
    difficulty: 1,
    prompt: 'Qual símbolo aparece mais vezes na sequência: ★ ◆ ★ ● ★ ◆ ★',
    options: ['◆', '★', '●', 'Todos iguais'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'O símbolo ★ aparece 4 vezes, mais que qualquer outro.',
    category: 'selective',
  },
  {
    id: 'att-e2',
    type: 'attention',
    difficulty: 1,
    prompt: 'Quantas vezes a letra "A" aparece na palavra ABACAXI?',
    options: ['1', '2', '3', '4'],
    correctIndex: 2,
    timeLimitMs: 15000,
    explanation: 'A letra "A" aparece nas posições 1, 3 e 5: A-B-A-C-A-X-I, totalizando 3 vezes.',
    category: 'selective',
  },
  {
    id: 'att-e3',
    type: 'attention',
    difficulty: 1,
    prompt: 'Na sequência ★ ● ★ ● ★ __, qual símbolo vem a seguir?',
    options: ['★', '●', '■', '▲'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'O padrão alterna entre ★ e ●. Após ★, o próximo é ●.',
    category: 'sustained',
  },
  {
    id: 'att-e4',
    type: 'attention',
    difficulty: 1,
    prompt: 'Quantos triângulos há nesta sequência? ▲ ● ▲ ■ ▲ ● ▲',
    options: ['2', '3', '4', '5'],
    correctIndex: 2,
    timeLimitMs: 15000,
    explanation: 'Há 4 triângulos (▲) nas posições 1, 3, 5 e 7 da sequência.',
    category: 'selective',
  },
  {
    id: 'att-e5',
    type: 'attention',
    difficulty: 1,
    prompt: 'Qual número aparece duas vezes na lista: 3, 7, 2, 9, 7, 5?',
    options: ['3', '7', '9', '5'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'O número 7 aparece na segunda e na quinta posição da sequência.',
    category: 'sustained',
  },

  // ===== DIFFICULTY 2 — Medium (5 questions) =====
  {
    id: 'att-m1',
    type: 'attention',
    difficulty: 2,
    prompt: 'Na sequência A-3-B-7-C-2-D, qual letra vem imediatamente antes do número 7?',
    options: ['A', 'B', 'C', 'D'],
    correctIndex: 1,
    timeLimitMs: 10000,
    explanation: 'Na sequência A-3-B-7-C-2-D, a letra B aparece imediatamente antes do 7.',
    category: 'selective',
  },
  {
    id: 'att-m2',
    type: 'attention',
    difficulty: 2,
    prompt: 'Observe a sequência de cores: Vermelho, Azul, Verde, Vermelho, Azul, __. Qual cor vem a seguir?',
    options: ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
    correctIndex: 2,
    timeLimitMs: 10000,
    explanation: 'O padrão se repete a cada 3 cores: Vermelho, Azul, Verde. A próxima é Verde.',
    category: 'sustained',
  },
  {
    id: 'att-m3',
    type: 'attention',
    difficulty: 2,
    prompt: 'Qual é a soma dos números pares na lista: 3, 8, 1, 4, 7, 2?',
    options: ['12', '14', '10', '16'],
    correctIndex: 1,
    timeLimitMs: 10000,
    explanation: 'Os números pares são 8, 4 e 2. A soma é 8 + 4 + 2 = 14.',
    category: 'divided',
  },
  {
    id: 'att-m4',
    type: 'attention',
    difficulty: 2,
    prompt: 'Na palavra PARALELEPÍPEDO, quantas vezes a letra "E" aparece?',
    options: ['1', '2', '3', '4'],
    correctIndex: 2,
    timeLimitMs: 10000,
    explanation: 'P-A-R-A-L-E-L-E-P-Í-P-E-D-O — a letra E aparece nas posições 6, 8 e 12, totalizando 3 vezes.',
    category: 'selective',
  },
  {
    id: 'att-m5',
    type: 'attention',
    difficulty: 2,
    prompt: 'Quantas palavras têm exatamente 4 letras: Sol, Mesa, Ar, Bolo, Luz, Casa?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
    timeLimitMs: 10000,
    explanation: 'As palavras com exatamente 4 letras são: Mesa, Bolo e Casa, totalizando 3.',
    category: 'divided',
  },

  // ===== DIFFICULTY 3 — Hard (5 questions) =====
  {
    id: 'att-h1',
    type: 'attention',
    difficulty: 3,
    prompt: 'Observe a grade e encontre o valor que falta:\n1  4  7\n2  5  8\n3  6  ?\nQual número substitui o "?"?',
    options: ['7', '8', '9', '10'],
    correctIndex: 2,
    timeLimitMs: 8000,
    explanation: 'Cada coluna aumenta de 1 em 1 (1,2,3 / 4,5,6 / 7,8,9). O valor é 9.',
    category: 'divided',
  },
  {
    id: 'att-h2',
    type: 'attention',
    difficulty: 3,
    prompt: 'Na sequência 1A-2B-3C-4D-5E, qual é o resultado de somar todos os números e subtrair a posição da letra C no alfabeto?',
    options: ['10', '12', '15', '8'],
    correctIndex: 1,
    timeLimitMs: 8000,
    explanation: 'Soma dos números: 1+2+3+4+5 = 15. A letra C é a 3ª no alfabeto. 15 - 3 = 12.',
    category: 'divided',
  },
  {
    id: 'att-h3',
    type: 'attention',
    difficulty: 3,
    prompt: 'Observe: 3, 6, 11, 18, 27, __. Qual número completa a sequência?',
    options: ['34', '36', '38', '40'],
    correctIndex: 2,
    timeLimitMs: 8000,
    explanation: 'As diferenças entre consecutivos são 3, 5, 7, 9 (ímpares crescentes). A próxima diferença é 11: 27 + 11 = 38.',
    category: 'sustained',
  },
  {
    id: 'att-h4',
    type: 'attention',
    difficulty: 3,
    prompt: 'Conte simultaneamente: quantos números pares E quantas vogais existem em "A2B4E6I8O"? Some os dois resultados.',
    options: ['6', '7', '8', '9'],
    correctIndex: 2,
    timeLimitMs: 8000,
    explanation: 'Números pares: 2, 4, 6, 8 = 4. Vogais: A, E, I, O = 4. Total: 4 + 4 = 8.',
    category: 'divided',
  },
  {
    id: 'att-h5',
    type: 'attention',
    difficulty: 3,
    prompt: 'Na sequência X-1-Y-2-X-3-Y-4-X-5-Y-__, qual número completa o padrão?',
    options: ['4', '5', '6', '7'],
    correctIndex: 2,
    timeLimitMs: 8000,
    explanation: 'Os números aumentam sequencialmente (1,2,3,4,5,...). Após 5, vem 6.',
    category: 'sustained',
  },
]
