import { Question } from '../types'

export const logicQuestions: Question[] = [
  // ===== DIFFICULTY 1 — Easy (5 questions) =====
  {
    id: 'log-e1',
    type: 'logic',
    difficulty: 1,
    prompt: 'Se todos os gatos são animais e Mimi é um gato, então Mimi é...?',
    options: ['Uma planta', 'Um animal', 'Um objeto', 'Uma pessoa'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'Silogismo básico: se todos os gatos são animais e Mimi é gato, Mimi necessariamente é um animal.',
    category: 'deductive',
  },
  {
    id: 'log-e2',
    type: 'logic',
    difficulty: 1,
    prompt: 'Complete a sequência: 2, 4, 6, 8, __',
    options: ['9', '10', '11', '12'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'A sequência aumenta de 2 em 2. Após 8, o próximo é 10.',
    category: 'pattern',
  },
  {
    id: 'log-e3',
    type: 'logic',
    difficulty: 1,
    prompt: 'João é mais alto que Pedro. Pedro é mais alto que Carlos. Quem é o mais baixo?',
    options: ['João', 'Pedro', 'Carlos', 'Não é possível saber'],
    correctIndex: 2,
    timeLimitMs: 15000,
    explanation: 'João > Pedro > Carlos. Carlos é o mais baixo dos três.',
    category: 'deductive',
  },
  {
    id: 'log-e4',
    type: 'logic',
    difficulty: 1,
    prompt: 'Cachorro está para latir assim como gato está para...?',
    options: ['Correr', 'Miar', 'Nadar', 'Voar'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'A relação é animal para seu som. Cachorro late, gato mia.',
    category: 'inductive',
  },
  {
    id: 'log-e5',
    type: 'logic',
    difficulty: 1,
    prompt: 'Se hoje é segunda-feira, que dia será daqui a 2 dias?',
    options: ['Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira'],
    correctIndex: 1,
    timeLimitMs: 15000,
    explanation: 'Segunda + 2 dias = quarta-feira (segunda, terça, quarta).',
    category: 'deductive',
  },

  // ===== DIFFICULTY 2 — Medium (5 questions) =====
  {
    id: 'log-m1',
    type: 'logic',
    difficulty: 2,
    prompt: 'Livro está para biblioteca assim como roupa está para...?',
    options: ['Loja', 'Guarda-roupa', 'Fábrica', 'Costureira'],
    correctIndex: 1,
    timeLimitMs: 12000,
    explanation: 'A relação é objeto para o lugar onde é guardado. Livros ficam na biblioteca, roupas no guarda-roupa.',
    category: 'inductive',
  },
  {
    id: 'log-m2',
    type: 'logic',
    difficulty: 2,
    prompt: 'Em uma fila, Ana está na 4ª posição contando do início e na 6ª contando do final. Quantas pessoas há na fila?',
    options: ['8', '9', '10', '11'],
    correctIndex: 1,
    timeLimitMs: 12000,
    explanation: 'Posição do início + posição do final - 1 = total. 4 + 6 - 1 = 9 pessoas.',
    category: 'deductive',
  },
  {
    id: 'log-m3',
    type: 'logic',
    difficulty: 2,
    prompt: 'Se nenhum peixe voa e todos os salmões são peixes, então:',
    options: ['Alguns salmões voam', 'Nenhum salmão voa', 'Todos os peixes são salmões', 'Alguns peixes voam'],
    correctIndex: 1,
    timeLimitMs: 12000,
    explanation: 'Se nenhum peixe voa e salmões são peixes, então nenhum salmão voa (silogismo categórico).',
    category: 'deductive',
  },
  {
    id: 'log-m4',
    type: 'logic',
    difficulty: 2,
    prompt: 'Qual número não pertence à sequência: 2, 3, 5, 7, 11, 14, 17?',
    options: ['3', '7', '14', '17'],
    correctIndex: 2,
    timeLimitMs: 12000,
    explanation: 'A sequência é de números primos (2, 3, 5, 7, 11, 13, 17). O número 14 não é primo (14 = 2 x 7).',
    category: 'pattern',
  },
  {
    id: 'log-m5',
    type: 'logic',
    difficulty: 2,
    prompt: 'Se Maria é mãe de João e João é pai de Lucas, qual é a relação de Maria com Lucas?',
    options: ['Mãe', 'Tia', 'Avó', 'Prima'],
    correctIndex: 2,
    timeLimitMs: 12000,
    explanation: 'Maria é mãe de João, e João é pai de Lucas. Portanto, Maria é avó de Lucas.',
    category: 'deductive',
  },

  // ===== DIFFICULTY 3 — Hard (5 questions) =====
  {
    id: 'log-h1',
    type: 'logic',
    difficulty: 3,
    prompt: 'Um fazendeiro tem galinhas e coelhos. No total são 20 cabeças e 56 patas. Quantas galinhas ele tem?',
    options: ['8', '10', '12', '14'],
    correctIndex: 2,
    timeLimitMs: 10000,
    explanation: 'Galinhas (G) têm 2 patas, coelhos (C) têm 4. G + C = 20 e 2G + 4C = 56. Resolvendo: C = 8, G = 12.',
    category: 'deductive',
  },
  {
    id: 'log-h2',
    type: 'logic',
    difficulty: 3,
    prompt: 'Todos os A são B. Alguns B são C. Nenhum C é D. Qual conclusão é válida?',
    options: ['Todos os A são C', 'Alguns A podem ser C', 'Nenhum A é D', 'Todos os B são D'],
    correctIndex: 1,
    timeLimitMs: 10000,
    explanation: 'Se todos os A são B e alguns B são C, é possível que alguns A estejam entre os B que são C. Mas não é certo.',
    category: 'deductive',
  },
  {
    id: 'log-h3',
    type: 'logic',
    difficulty: 3,
    prompt: 'Em uma sala, 60% falam inglês e 40% falam espanhol. Se 20% falam ambos, qual porcentagem fala pelo menos um dos idiomas?',
    options: ['70%', '80%', '90%', '100%'],
    correctIndex: 1,
    timeLimitMs: 10000,
    explanation: 'Princípio da inclusão-exclusão: P(A ou B) = P(A) + P(B) - P(A e B) = 60% + 40% - 20% = 80%.',
    category: 'inductive',
  },
  {
    id: 'log-h4',
    type: 'logic',
    difficulty: 3,
    prompt: 'Se invertermos a proposição "Se chove, então a rua fica molhada", a contrapositiva logicamente equivalente é:',
    options: [
      'Se a rua fica molhada, então chove',
      'Se não chove, a rua não fica molhada',
      'Se a rua não fica molhada, então não chove',
      'Chove e a rua não fica molhada',
    ],
    correctIndex: 2,
    timeLimitMs: 10000,
    explanation: 'A contrapositiva de "Se P então Q" é "Se não Q então não P". Ambas são logicamente equivalentes.',
    category: 'deductive',
  },
  {
    id: 'log-h5',
    type: 'logic',
    difficulty: 3,
    prompt: 'Um caracol sobe 3 metros de dia e escorrega 2 metros à noite. Se o poço tem 10 metros, em quantos dias ele sai?',
    options: ['7', '8', '9', '10'],
    correctIndex: 1,
    timeLimitMs: 10000,
    explanation: 'A cada dia completo sobe 1 metro líquido. Após 7 dias está a 7m. No 8º dia sobe 3m, chegando a 10m e saindo antes de escorregar.',
    category: 'pattern',
  },
]
